apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
  labels:
    app.kubernetes.io/name: sovereign-command-center
    app.kubernetes.io/part-of: sovereign-defense-lab
    sovereign.io/layer: telemetry
    sovereign.io/isolated: 'true'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: telemetry-quota
  namespace: telemetry
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 2Gi
    limits.cpu: '2'
    limits.memory: 4Gi
    pods: '16'
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: telemetry-allow-simulation-ingress
  namespace: telemetry
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              sovereign.io/layer: simulation
